### ISSUE TITLE
Mirrored rss-box to GitLab with a Pages site!

### ISSUE THREAD

**Issue by adnan360** [p3k/rss-box#12]
I like this project as a quick RSS/Atom feed checker. I saw you had a non-profit notice on your website and was requesting to self-host. So went ahead and mirrored it to GitLab with a Pages site: [https://adnan360.gitlab.io/rss-box/](https://adnan360.gitlab.io/rss-box/)

I wrote a [blog](https://socialhome.network/content/8719474/) about it if anyone's interested.

Thanks for creating this.

**Comment by p3k** [comment]
hi @adnan360 thanks for your message. i am glad you like this long-running little project.

i understand why you do not like github so much. it’s a mixed bag. i use gitlab for some other projects, too, and think it’s a great alternative.

it’s nice you noted and even followed the suggestion to self-host the project – though i am not sure if the wording is misleading because actually the important part is to host and run the [jsonp proxy](https://github.com/p3k/json3k) on your own.

in your blog post you write:

> It just needs a basic server for fetching the feed content, which is gladly supported by GitLab pages.

if this is the case that would be very cool and i’d like to know more about it. 

nevertheless, at the time of writing this, your rss-box page still requests the rss jsonp from my server. while this is not what i consider self-hosting it shouldn’t be a problem either as long as your page sends a reasonable amount of requests.

![image](https://user-images.githubusercontent.com/16631/107880583-117bfc80-6ee0-11eb-8fa0-801652248d93.png)

btw. you mention the user interface as dated – if you feel like improving your version maybe the resulting ui could become the default…?

**Comment by adnan360** [comment]
> it’s nice you noted and even followed the suggestion to self-host the project – though i am not sure if the wording is misleading because actually the important part is to host and run the jsonp proxy on your own.

Oh, sorry! I didn't check this. I used this on my local setup, plus GitLab pages and it worked, so I assumed it was using Javascript's [fetch API](https://developer.mozilla.org/en-US/docs/Web/API/Fetch_API/Using_Fetch) for this.

I've skimmed through the json3k readme but not entirely sure why you used that. Is it to get around CORS policy? Can fetch api be used instead? I've used it for resources on same server and it works on GitLab pages. Didn't try to fetch from other servers though. That would make it so much easier to host and would be entirely client side.

> btw. you mention the user interface as dated – if you feel like improving your version maybe the resulting ui could become the default…?

Sure. I'm not certain if I'm a good designer, but if I get some spare time I'll surely post a PR for that.

**Comment by p3k** [comment]
> I assumed it was using Javascript's fetch API for this

nope unfortunately that does not work for most rss feeds.

> I've skimmed through the json3k readme but not entirely sure why you used that. Is it to get around CORS policy?

exactly.

> Can fetch api be used instead?

it would be great if it could but alas it cannot. i agree, entirely client-side would be so much easier. 

on the other hand, the server also takes some of the burden from the feed providers (caching) and i think it’s still the better way to do this.

**Comment by adnan360** [comment]
> nope unfortunately that does not work for most rss feeds.

They should've thought about these use cases when implementing an API like this. It would've been much simpler this way. Maybe browsers should've put a confirm dialog box somewhere if they were that worried about security. At least that should've been a parameter as an option.

> on the other hand, the server also takes some of the burden from the feed providers (caching) and i think it’s still the better way to do this.

I guess so.

> ...the important part is to host and run the jsonp proxy on your own.
> ...it shouldn’t be a problem either as long as your page sends a reasonable amount of requests.

No worries. I've implemented a [basic working json proxy](https://gitlab.com/-/snippets/2077169) in PHP and changed the config on my fork to work from my domain. It doesn't send any header info yet, but it works. I haven't got the chance to look into a PHP alternative for "ferris" referrer. So I've emptied the referrer value for now, so referrer feature won't work on my mirror. Also changed the default feed url so that p3k.org doesn't get a hit from the mirror.

**Comment by p3k** [comment]
> I've implemented a basic working json proxy in PHP

excellent. i assume this only works for the rss box page at github.io not if the script snippet is embedded somewhere else, right? (just curious, no biggie.)

don’t worry about the ferris script, either. as far as i understood this is beyond what you are using the rss boxes for, anyway.

> I'm grateful to you for creating this project. Thanks a lot.

you’re very welcome. thanks to you, too, for the feedback. please don’t hesitate to get back to me with further questions, suggestions or ideas.

btw. thanks to you i now got to know socialhome. i am running my own server since the 2000s and a long time user of yunohost (which is not as federated) – alwasy very interested in these independent solutions, albeit rather from a lurking perspective, yet.

take care!

**Comment by adnan360** [comment]
> excellent. i assume this only works for the rss box page at github.io not if the script snippet is embedded somewhere else, right? (just curious, no biggie.)

Good thing you pointed it out. I was worried about that too a bit.

I changed `src/local.js` (un-gitignored it on my fork to include it in commit so that values are kept there intact, just in case). Then ran `yarn build` to populate `dist`. That seemed to do the trick. I tested the code snippet on my local setup and it points to my domain instead. Also I edited package.json's commands to copy files of `dist` to `public` when build/watch is run. So now I won't have to manually copy it.

> btw. thanks to you i now got to know socialhome. i am running my own server since the 2000s and a long time user of yunohost (which is not as federated) – alwasy very interested in these independent solutions, albeit rather from a lurking perspective, yet.

I learned about socialhome when I was looking for a fediverse solution of a blog. I think I found it from www.fediverse.party.

This is nothing compared to what else is out there. You should join Mastodon/Pleroma if you are not already. I'm available on `@adnan360@mas.to`. There are lots of other cool stuff people post there. You would be amazed.
